services:
  - type: web
    name: gleis13
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    build:
      pythonVersion: 3.10.13
    envVars:
      - key: OPENAI_API_KEY
        sync: false